language: minimal
os: linux
arch: amd64
dist: focal
branches: 
  except:
    - CI-latest
script:
- sudo apt-get install -y libusb-1.0-0-dev
- sudo apt-get install -y libgif-dev
- sudo apt-get install -y libpng-dev
- make
before_deploy:
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    export TRAVIS_TAG=CI-latest
  fi
deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file: 
  - $TRAVIS_BUILD_DIR/bin
  skip_cleanup: true
  prerelease: true
  draft: false
  overwrite: true
  on:
    tags: false
    branch: master
