language: minimal
os: linux
arch: amd64
dist: focal
branches: 
  except:
    - CI-latest
script:
- sudo apt-get install -y libusb-1.0-0-dev
- sudo apt-get install -y libgif-dev
- sudo apt-get install -y libpng-dev
- make
- |
  echo TRAVIS_TAG=$TRAVIS_TAG
  echo TRAVIS_BRANCH=$TRAVIS_BRANCH
  if [[ -z "$TRAVIS_TAG" ]]; then
    export TRAVIS_TAG=CI-latest
    git tag -f $TRAVIS_TAG
  fi
before_deploy:
deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: 
  - $TRAVIS_BUILD_DIR/bin/*
  skip_cleanup: true
  prerelease: true
  draft: false
  overwrite: true
  on:
    tags: true
    branch: master
